from .auto_upload_image_to_pixxio_collection import NODE_CLASS_MAPPINGS as AUTO_UPLOAD_MAPPINGS
from .auto_upload_image_to_pixxio_collection import NODE_DISPLAY_NAME_MAPPINGS as AUTO_UPLOAD_DISPLAY_MAPPINGS
from .load_from_pixxio import NODE_CLASS_MAPPINGS as LOAD_MAPPINGS
from .load_from_pixxio import NODE_DISPLAY_NAME_MAPPINGS as LOAD_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(AUTO_UPLOAD_MAPPINGS)
NODE_CLASS_MAPPINGS.update(LOAD_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(AUTO_UPLOAD_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(LOAD_DISPLAY_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']